# Generated by Django 3.0.3 on 2020-05-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsRecived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('rollno', models.IntegerField()),
                ('passward', models.CharField(max_length=20)),
                ('ans_1', models.CharField(max_length=200)),
                ('ans_2', models.CharField(max_length=200)),
                ('ans_3', models.CharField(max_length=200)),
                ('ans_4', models.CharField(max_length=200)),
                ('ans_5', models.CharField(max_length=200)),
                ('ans_6', models.CharField(max_length=200)),
                ('ans_7', models.CharField(max_length=200)),
                ('ans_8', models.CharField(max_length=200)),
                ('ans_9', models.CharField(max_length=200)),
                ('ans_10', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=20)),
                ('passward', models.CharField(max_length=20, unique=True)),
                ('key', models.CharField(max_length=20, unique=True)),
                ('question_1', models.CharField(max_length=100)),
                ('q_1_opt_1', models.CharField(max_length=200)),
                ('q_1_opt_2', models.CharField(max_length=200)),
                ('q_1_opt_3', models.CharField(max_length=200)),
                ('q_1_opt_4', models.CharField(max_length=200)),
                ('question_2', models.CharField(max_length=100)),
                ('q_2_opt_1', models.CharField(max_length=200)),
                ('q_2_opt_2', models.CharField(max_length=200)),
                ('q_2_opt_3', models.CharField(max_length=200)),
                ('q_2_opt_4', models.CharField(max_length=200)),
                ('question_3', models.CharField(max_length=100)),
                ('q_3_opt_1', models.CharField(max_length=200)),
                ('q_3_opt_2', models.CharField(max_length=200)),
                ('q_3_opt_3', models.CharField(max_length=200)),
                ('q_3_opt_4', models.CharField(max_length=200)),
                ('question_4', models.CharField(max_length=100)),
                ('q_4_opt_1', models.CharField(max_length=200)),
                ('q_4_opt_2', models.CharField(max_length=200)),
                ('q_4_opt_3', models.CharField(max_length=200)),
                ('q_4_opt_4', models.CharField(max_length=200)),
                ('question_5', models.CharField(max_length=100)),
                ('q_5_opt_1', models.CharField(max_length=200)),
                ('q_5_opt_2', models.CharField(max_length=200)),
                ('q_5_opt_3', models.CharField(max_length=200)),
                ('q_5_opt_4', models.CharField(max_length=200)),
                ('question_6', models.CharField(max_length=100)),
                ('q_6_opt_1', models.CharField(max_length=200)),
                ('q_6_opt_2', models.CharField(max_length=200)),
                ('q_6_opt_3', models.CharField(max_length=200)),
                ('q_6_opt_4', models.CharField(max_length=200)),
                ('question_7', models.CharField(max_length=100)),
                ('q_7_opt_1', models.CharField(max_length=200)),
                ('q_7_opt_2', models.CharField(max_length=200)),
                ('q_7_opt_3', models.CharField(max_length=200)),
                ('q_7_opt_4', models.CharField(max_length=200)),
                ('question_8', models.CharField(max_length=100)),
                ('q_8_opt_1', models.CharField(max_length=200)),
                ('q_8_opt_2', models.CharField(max_length=200)),
                ('q_8_opt_3', models.CharField(max_length=200)),
                ('question_9', models.CharField(max_length=100)),
                ('q_9_opt_1', models.CharField(max_length=200)),
                ('q_9_opt_2', models.CharField(max_length=200)),
                ('q_9_opt_3', models.CharField(max_length=200)),
                ('q_9_opt_4', models.CharField(max_length=200)),
                ('question_10', models.CharField(max_length=100)),
                ('q_10_opt_1', models.CharField(max_length=200)),
                ('q_10_opt_2', models.CharField(max_length=200)),
                ('q_10_opt_3', models.CharField(max_length=200)),
                ('q_10_opt_4', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('rollno', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
