# Generated by Django 3.0.3 on 2020-05-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=20)),
                ('passward', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='test',
            old_name='key',
            new_name='key_or_passward_to_give_test_share',
        ),
        migrations.RemoveField(
            model_name='test',
            name='passward',
        ),
        migrations.AlterField(
            model_name='test',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.Teacher'),
        ),
    ]
