# Generated by Django 3.0.3 on 2020-05-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_auto_20200510_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ansrecived',
            old_name='passward',
            new_name='key',
        ),
    ]
